spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: biblioteca
  redis:
    host: redis
    port: 6379

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
      mongodb:
        driver:
          protocol:
            command: DEBUG